/**
 * API types — placeholder generated from OpenAPI spec.
 *
 * WARNING: This file is auto-generated by `pnpm gen:types`.
 * Do NOT edit manually. Any manual changes will be overwritten.
 *
 * TODO: Implement the codegen script that reads the backend's
 * /v3/api-docs OpenAPI JSON and produces this file.
 */

// ─── Common ───────────────────────────────────────────────

export interface PageMeta {
  nextCursor: string | null;
  hasMore: boolean;
}

export interface PaginatedResponse<T> {
  data: T[];
  page: PageMeta;
}

// ─── Problem Details (RFC 7807) ──────────────────────────

export interface ProblemDetailError {
  field: string;
  code: string;
  message: string;
}

export interface ProblemDetail {
  type: string;
  title: string;
  status: number;
  code: string;
  errors?: ProblemDetailError[];
  traceId?: string;
}

// ─── Auth ─────────────────────────────────────────────────

export interface User {
  id: string;
  email: string;
  name: string;
  avatarUrl?: string;
}

export interface OrganizationMembership {
  id: string;
  name: string;
  slug: string;
  role: "OWNER" | "ADMIN" | "MEMBER";
}

export interface MeResponse {
  user: User;
  organizations: OrganizationMembership[];
}

export interface RegisterRequest {
  email: string;
  name: string;
  password: string;
  organizationName?: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterResponse {
  user: User;
  organizations: OrganizationMembership[];
}

// ─── Organization ─────────────────────────────────────────

export interface Organization {
  id: string;
  name: string;
  slug: string;
  role: "OWNER" | "ADMIN" | "MEMBER";
}

// ─── Project ──────────────────────────────────────────────

export type ProjectEnvironment = "PRODUCTION" | "STAGING" | "DEVELOPMENT";

export interface Project {
  id: string;
  name: string;
  slug: string;
  publicKey: string;
  environment: ProjectEnvironment;
  allowedOrigins: string[];
  createdAt: string;
}

export interface CreateProjectRequest {
  name: string;
  environment: ProjectEnvironment;
  allowedOrigins?: string[];
}

// ─── Feedback ─────────────────────────────────────────────

export type FeedbackType = "BUG" | "FEATURE" | "IMPROVEMENT" | "QUESTION";

export type FeedbackStatus =
  | "NEW"
  | "TRIAGED"
  | "IN_PROGRESS"
  | "RESOLVED"
  | "CLOSED";

export type FeedbackPriority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";

export type FeedbackSource = "WIDGET" | "MANUAL" | "API";

export interface FeedbackContext {
  url: string;
  route: string;
  browser: string;
  browserVersion: string;
  operatingSystem: string;
  viewport: { width: number; height: number };
  appVersion: string;
}

export interface FeedbackTag {
  id: string;
  name: string;
  color: string;
}

export interface Feedback {
  id: string;
  type: FeedbackType;
  status: FeedbackStatus;
  priority: FeedbackPriority;
  source: FeedbackSource;
  title: string;
  description: string;
  reporter: User | null;
  externalUser?: { id: string; email: string };
  context?: FeedbackContext;
  metadata?: Record<string, unknown>;
  technicalContext?: Record<string, unknown>;
  screenshotUrl?: string;
  tags: FeedbackTag[];
  issue: { id: string; title: string } | null;
  createdAt: string;
}

export interface FeedbackFilters {
  type?: FeedbackType;
  status?: FeedbackStatus;
  priority?: FeedbackPriority;
  tagId?: string;
  issueId?: "none" | "any" | string;
  q?: string;
  from?: string;
  to?: string;
  sort?: "createdAt" | "priority";
  order?: "desc" | "asc";
  cursor?: string;
  limit?: number;
}

// ─── Issue ────────────────────────────────────────────────

export type IssueStatus =
  | "OPEN"
  | "IN_PROGRESS"
  | "RESOLVED"
  | "CLOSED";

export interface Issue {
  id: string;
  title: string;
  description?: string;
  status: IssueStatus;
  priority: FeedbackPriority;
  assignee?: User;
  feedbackCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateIssueRequest {
  title: string;
  description?: string;
  priority?: FeedbackPriority;
}

// ─── Tag ──────────────────────────────────────────────────

export interface Tag {
  id: string;
  name: string;
  color: string;
  createdAt: string;
}

export interface CreateTagRequest {
  name: string;
  color: string;
}

// ─── Comment ──────────────────────────────────────────────

export interface Comment {
  id: string;
  body: string;
  author: User;
  createdAt: string;
}

export interface CreateCommentRequest {
  body: string;
}

// ─── Audit ────────────────────────────────────────────────

export interface AuditLog {
  id: string;
  entityType: string;
  entityId: string;
  action: string;
  userId: string;
  userName: string;
  data?: Record<string, unknown>;
  createdAt: string;
}

// ─── Invitation ───────────────────────────────────────────

export interface Invitation {
  id: string;
  email: string;
  role: "ADMIN" | "MEMBER";
  token: string;
  expiresAt: string;
  createdAt: string;
}

export interface InvitationInfo {
  organizationName: string;
  email: string;
  role: string;
}
